export const designThemes = {
  minimal: {
    name: "Minimal",
    description: "Clean and simple",
    colors: {
      bg: "bg-white",
      header: "bg-gray-100",
      accent: "text-blue-600",
      button: "bg-blue-600 hover:bg-blue-700",
      card: "bg-gray-50 border border-gray-200",
      footer: "bg-gray-900 text-gray-300",
    },
    logoStyle: "minimal" as const,
  },
  modern: {
    name: "Modern",
    description: "Dark contemporary",
    colors: {
      bg: "bg-slate-950",
      header: "bg-slate-900",
      accent: "text-cyan-400",
      button: "bg-cyan-500 hover:bg-cyan-600",
      card: "bg-slate-800 border border-slate-700",
      footer: "bg-slate-900 text-slate-400",
    },
    logoStyle: "modern" as const,
  },
  bold: {
    name: "Bold",
    description: "Red vibrant",
    colors: {
      bg: "bg-gradient-to-br from-red-50 to-orange-50",
      header: "bg-gradient-to-r from-red-600 to-orange-600",
      accent: "text-red-600",
      button: "bg-red-600 hover:bg-red-700",
      card: "bg-white border-2 border-red-300",
      footer: "bg-red-900 text-red-100",
    },
    logoStyle: "bold" as const,
  },
  classic: {
    name: "Classic",
    description: "Purple elegant",
    colors: {
      bg: "bg-gradient-to-b from-purple-50 to-pink-50",
      header: "bg-gradient-to-r from-purple-700 to-pink-600",
      accent: "text-purple-700",
      button: "bg-purple-600 hover:bg-purple-700",
      card: "bg-white border border-purple-200",
      footer: "bg-purple-900 text-purple-100",
    },
    logoStyle: "classic" as const,
  },
  vibrant: {
    name: "Vibrant",
    description: "Neon energy",
    colors: {
      bg: "bg-gradient-to-br from-cyan-900 via-blue-900 to-purple-900",
      header: "bg-gradient-to-r from-cyan-400 to-blue-500",
      accent: "text-cyan-300",
      button: "bg-cyan-500 hover:bg-cyan-400",
      card: "bg-blue-900 border border-cyan-400",
      footer: "bg-black text-cyan-300",
    },
    logoStyle: "vibrant" as const,
  },
  tropical: {
    name: "Tropical",
    description: "Green paradise",
    colors: {
      bg: "bg-gradient-to-br from-green-50 to-emerald-50",
      header: "bg-gradient-to-r from-green-600 to-emerald-500",
      accent: "text-green-600",
      button: "bg-green-600 hover:bg-green-700",
      card: "bg-white border border-green-300",
      footer: "bg-green-900 text-green-100",
    },
    logoStyle: "minimal" as const,
  },
  sunset: {
    name: "Sunset",
    description: "Orange glow",
    colors: {
      bg: "bg-gradient-to-br from-orange-100 to-yellow-100",
      header: "bg-gradient-to-r from-orange-600 to-red-500",
      accent: "text-orange-600",
      button: "bg-orange-600 hover:bg-orange-700",
      card: "bg-white border border-orange-300",
      footer: "bg-orange-900 text-orange-100",
    },
    logoStyle: "bold" as const,
  },
  ocean: {
    name: "Ocean",
    description: "Blue waters",
    colors: {
      bg: "bg-gradient-to-br from-blue-50 to-cyan-50",
      header: "bg-gradient-to-r from-blue-600 to-cyan-500",
      accent: "text-blue-600",
      button: "bg-blue-600 hover:bg-blue-700",
      card: "bg-white border border-blue-300",
      footer: "bg-blue-900 text-blue-100",
    },
    logoStyle: "modern" as const,
  },
  midnight: {
    name: "Midnight",
    description: "Dark mystique",
    colors: {
      bg: "bg-gray-950",
      header: "bg-black",
      accent: "text-gray-300",
      button: "bg-gray-700 hover:bg-gray-600",
      card: "bg-gray-900 border border-gray-700",
      footer: "bg-black text-gray-400",
    },
    logoStyle: "vibrant" as const,
  },
  lavender: {
    name: "Lavender",
    description: "Soft purple",
    colors: {
      bg: "bg-gradient-to-br from-purple-100 to-pink-100",
      header: "bg-gradient-to-r from-purple-500 to-pink-500",
      accent: "text-purple-600",
      button: "bg-purple-500 hover:bg-purple-600",
      card: "bg-white border border-purple-200",
      footer: "bg-purple-800 text-purple-100",
    },
    logoStyle: "classic" as const,
  },
  gold: {
    name: "Gold",
    description: "Luxe premium",
    colors: {
      bg: "bg-gradient-to-br from-yellow-50 to-amber-50",
      header: "bg-gradient-to-r from-yellow-600 to-amber-600",
      accent: "text-yellow-700",
      button: "bg-yellow-600 hover:bg-yellow-700",
      card: "bg-white border border-yellow-300",
      footer: "bg-yellow-900 text-yellow-100",
    },
    logoStyle: "classic" as const,
  },
  forest: {
    name: "Forest",
    description: "Deep green",
    colors: {
      bg: "bg-gradient-to-br from-emerald-900 to-green-900",
      header: "bg-gradient-to-r from-emerald-700 to-green-700",
      accent: "text-emerald-300",
      button: "bg-emerald-600 hover:bg-emerald-700",
      card: "bg-emerald-800 border border-emerald-600",
      footer: "bg-black text-emerald-200",
    },
    logoStyle: "vibrant" as const,
  },
  cherry: {
    name: "Cherry",
    description: "Deep red",
    colors: {
      bg: "bg-gradient-to-br from-rose-50 to-red-50",
      header: "bg-gradient-to-r from-rose-700 to-red-600",
      accent: "text-rose-700",
      button: "bg-rose-600 hover:bg-rose-700",
      card: "bg-white border border-rose-300",
      footer: "bg-rose-900 text-rose-100",
    },
    logoStyle: "bold" as const,
  },
  indigo: {
    name: "Indigo",
    description: "Deep blue",
    colors: {
      bg: "bg-gradient-to-br from-indigo-50 to-blue-50",
      header: "bg-gradient-to-r from-indigo-700 to-blue-600",
      accent: "text-indigo-700",
      button: "bg-indigo-600 hover:bg-indigo-700",
      card: "bg-white border border-indigo-300",
      footer: "bg-indigo-900 text-indigo-100",
    },
    logoStyle: "modern" as const,
  },
  coral: {
    name: "Coral",
    description: "Warm coral",
    colors: {
      bg: "bg-gradient-to-br from-orange-50 to-pink-50",
      header: "bg-gradient-to-r from-orange-500 to-pink-500",
      accent: "text-orange-600",
      button: "bg-orange-500 hover:bg-orange-600",
      card: "bg-white border border-orange-200",
      footer: "bg-orange-800 text-orange-100",
    },
    logoStyle: "bold" as const,
  },
  mint: {
    name: "Mint",
    description: "Fresh mint",
    colors: {
      bg: "bg-gradient-to-br from-green-50 to-teal-50",
      header: "bg-gradient-to-r from-green-500 to-teal-500",
      accent: "text-green-600",
      button: "bg-green-500 hover:bg-green-600",
      card: "bg-white border border-green-200",
      footer: "bg-green-800 text-green-100",
    },
    logoStyle: "minimal" as const,
  },
  plum: {
    name: "Plum",
    description: "Deep plum",
    colors: {
      bg: "bg-gradient-to-br from-purple-100 to-indigo-100",
      header: "bg-gradient-to-r from-purple-700 to-indigo-600",
      accent: "text-purple-700",
      button: "bg-purple-600 hover:bg-purple-700",
      card: "bg-white border border-purple-300",
      footer: "bg-purple-900 text-purple-100",
    },
    logoStyle: "classic" as const,
  },
  slate: {
    name: "Slate",
    description: "Cool gray",
    colors: {
      bg: "bg-gradient-to-br from-slate-100 to-gray-100",
      header: "bg-gradient-to-r from-slate-700 to-gray-600",
      accent: "text-slate-700",
      button: "bg-slate-600 hover:bg-slate-700",
      card: "bg-white border border-slate-300",
      footer: "bg-slate-900 text-slate-200",
    },
    logoStyle: "minimal" as const,
  },
  lemon: {
    name: "Lemon",
    description: "Bright yellow",
    colors: {
      bg: "bg-gradient-to-br from-yellow-100 to-lime-100",
      header: "bg-gradient-to-r from-yellow-500 to-lime-500",
      accent: "text-yellow-600",
      button: "bg-yellow-500 hover:bg-yellow-600",
      card: "bg-white border border-yellow-300",
      footer: "bg-yellow-800 text-yellow-100",
    },
    logoStyle: "bold" as const,
  },
  teal: {
    name: "Teal",
    description: "Teal waters",
    colors: {
      bg: "bg-gradient-to-br from-teal-50 to-cyan-50",
      header: "bg-gradient-to-r from-teal-600 to-cyan-500",
      accent: "text-teal-600",
      button: "bg-teal-600 hover:bg-teal-700",
      card: "bg-white border border-teal-300",
      footer: "bg-teal-900 text-teal-100",
    },
    logoStyle: "modern" as const,
  },
  rose: {
    name: "Rose",
    description: "Soft rose",
    colors: {
      bg: "bg-gradient-to-br from-rose-50 to-pink-50",
      header: "bg-gradient-to-r from-rose-500 to-pink-500",
      accent: "text-rose-600",
      button: "bg-rose-500 hover:bg-rose-600",
      card: "bg-white border border-rose-200",
      footer: "bg-rose-800 text-rose-100",
    },
    logoStyle: "classic" as const,
  },
  charcoal: {
    name: "Charcoal",
    description: "Dark charcoal",
    colors: {
      bg: "bg-gradient-to-br from-gray-900 to-slate-900",
      header: "bg-gradient-to-r from-gray-800 to-slate-800",
      accent: "text-gray-300",
      button: "bg-gray-700 hover:bg-gray-600",
      card: "bg-gray-800 border border-gray-700",
      footer: "bg-black text-gray-300",
    },
    logoStyle: "vibrant" as const,
  },
  lime: {
    name: "Lime",
    description: "Bright lime",
    colors: {
      bg: "bg-gradient-to-br from-lime-50 to-green-50",
      header: "bg-gradient-to-r from-lime-600 to-green-600",
      accent: "text-lime-600",
      button: "bg-lime-600 hover:bg-lime-700",
      card: "bg-white border border-lime-300",
      footer: "bg-lime-900 text-lime-100",
    },
    logoStyle: "minimal" as const,
  },
  fuchsia: {
    name: "Fuchsia",
    description: "Bold fuchsia",
    colors: {
      bg: "bg-gradient-to-br from-fuchsia-50 to-pink-50",
      header: "bg-gradient-to-r from-fuchsia-600 to-pink-600",
      accent: "text-fuchsia-600",
      button: "bg-fuchsia-600 hover:bg-fuchsia-700",
      card: "bg-white border border-fuchsia-300",
      footer: "bg-fuchsia-900 text-fuchsia-100",
    },
    logoStyle: "bold" as const,
  },
  sky: {
    name: "Sky",
    description: "Light sky",
    colors: {
      bg: "bg-gradient-to-br from-sky-50 to-blue-50",
      header: "bg-gradient-to-r from-sky-500 to-blue-500",
      accent: "text-sky-600",
      button: "bg-sky-500 hover:bg-sky-600",
      card: "bg-white border border-sky-300",
      footer: "bg-sky-800 text-sky-100",
    },
    logoStyle: "modern" as const,
  },
  amber: {
    name: "Amber",
    description: "Warm amber",
    colors: {
      bg: "bg-gradient-to-br from-amber-50 to-yellow-50",
      header: "bg-gradient-to-r from-amber-600 to-yellow-500",
      accent: "text-amber-700",
      button: "bg-amber-600 hover:bg-amber-700",
      card: "bg-white border border-amber-300",
      footer: "bg-amber-900 text-amber-100",
    },
    logoStyle: "bold" as const,
  },
  violet: {
    name: "Violet",
    description: "Deep violet",
    colors: {
      bg: "bg-gradient-to-br from-violet-50 to-purple-50",
      header: "bg-gradient-to-r from-violet-600 to-purple-600",
      accent: "text-violet-600",
      button: "bg-violet-600 hover:bg-violet-700",
      card: "bg-white border border-violet-300",
      footer: "bg-violet-900 text-violet-100",
    },
    logoStyle: "classic" as const,
  },
};

export type DesignThemeName = keyof typeof designThemes;
